/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/character/scene.gltf --transform --types 
Files: public/models/character/scene.gltf [55.15KB] > C:\temp\Posture_game_3d\scene-transformed.glb [87.24KB] (-58%)
Author: 3Dimentional (https://sketchfab.com/insectscorch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-female-base-mesh-155415df28d14191aca2be1abf65c9ac
Title: Toon Female Base Mesh
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function CharacterModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/character/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.5, 0]} rotation={[0, Math.PI, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0, 8.038, -0.09]} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial002} position={[0, 7.601, 0.184]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/character/scene-transformed.glb')
