/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rocks/scene.gltf --transform --types 
Files: public/models/rocks/scene.gltf [4.96KB] > C:\temp\Posture_game_3d\scene-transformed.glb [1.86MB] (-37464%)
Author: mdsz13 (https://sketchfab.com/shaz13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mossy-rocks-low-poly-6823a52d39ec40be9a911384f662a466
Title: Mossy Rocks Low Poly
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function RockModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rocks/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material} position={[0, 0, 0]} scale={[0.1, 0.08, 0.1]} />
    </group>
  )
}

useGLTF.preload('/models/rocks/scene-transformed.glb')
