/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/trees/scene.gltf --transform --types 
Files: public/models/trees/scene.gltf [38.95KB] > C:\temp\Posture_game_3d\scene-transformed.glb [2.11MB] (-5307%)
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-trees-collection-fe67c886eebf4bcb988d7c45e69995ad
Title: Realistic Trees Collection
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Tree_EZTree0Large_branches_0: THREE.Mesh
    Tree_EZTree0Large_leaves_0: THREE.Mesh
    Tree_EZTree0Medium010_leaves010_0: THREE.Mesh
    Tree_EZTree1Bush006_leaves006_0: THREE.Mesh
    Tree_EZTree1Bush006_branches006_0: THREE.Mesh
  }
  materials: {
    branches: THREE.MeshStandardMaterial
    leaves: THREE.MeshStandardMaterial
    ['leaves.010']: THREE.MeshStandardMaterial
    ['leaves.006']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function TreeModel({ variant = 'large', ...props }: JSX.IntrinsicElements['group'] & { variant?: 'large' | 'medium' | 'bush' }) {
  const { nodes, materials } = useGLTF('/models/trees/scene-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      {variant === 'large' && (
        <group position={[0, -1.5, 0]}>
          <mesh geometry={nodes.Tree_EZTree0Large_branches_0.geometry} material={materials.branches} rotation={[-0.037, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Tree_EZTree0Large_leaves_0.geometry} material={materials.leaves} rotation={[-0.037, 0, 0]} scale={0.01} />
        </group>
      )}
      {variant === 'medium' && (
        <group position={[0, -1.0, 0]}>
          <mesh geometry={nodes.Tree_EZTree0Medium010_leaves010_0.geometry} material={materials['leaves.010']} rotation={[-0.037, 0, 0]} scale={0.01} />
        </group>
      )}
      {variant === 'bush' && (
        <group position={[0, -0.5, 0]}>
          <mesh geometry={nodes.Tree_EZTree1Bush006_leaves006_0.geometry} material={materials['leaves.006']} rotation={[-0.037, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Tree_EZTree1Bush006_branches006_0.geometry} material={materials.material_0} rotation={[-0.037, 0, 0]} scale={0.01} />
        </group>
      )}
    </group>
  )
}

useGLTF.preload('/models/trees/scene-transformed.glb')
